import {
  Signal,
  MarketCenter,
  GeoEvent,
  PortfolioHolding,
  FAQ,
  Testimonial,
  RiskMetric,
  PricingTier,
  NavItem,
} from "./types"

export const TRADING_SIGNALS: Signal[] = [
  {
    id: "sig_001",
    ticker: "XAUUSD",
    name: "Gold Futures",
    direction: "BUY",
    confidence: 87,
    assetClass: "Commodities",
    currentPrice: 2145.50,
    changePercent: 2.34,
    entry: 2120.00,
    stopLoss: 2095.00,
    target: 2200.00,
    riskReward: 3.2,
    atr: 18.50,
    maxPosition: 50000,
    triggeringEvent: "Fed rate pause expectations",
    tags: ["commodity", "safe-haven", "technical-breakout"],
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "sig_002",
    ticker: "NIFTY50",
    name: "NIFTY 50 Index",
    direction: "HOLD",
    confidence: 62,
    assetClass: "Equities",
    currentPrice: 22847.45,
    changePercent: -1.23,
    entry: 23100.00,
    stopLoss: 22500.00,
    target: 23500.00,
    riskReward: 1.95,
    atr: 285.30,
    maxPosition: 100000,
    triggeringEvent: "Consolidation phase near resistance",
    tags: ["index", "india", "consolidation"],
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "sig_003",
    ticker: "RELIANCE",
    name: "Reliance Industries",
    direction: "BUY",
    confidence: 75,
    assetClass: "Equities",
    currentPrice: 2987.65,
    changePercent: 3.45,
    entry: 2920.00,
    stopLoss: 2850.00,
    target: 3150.00,
    riskReward: 2.57,
    atr: 65.20,
    maxPosition: 75000,
    triggeringEvent: "Earnings beat + dividend announcement",
    tags: ["largecap", "energy", "fundamental"],
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "sig_004",
    ticker: "SPXL",
    name: "Direxion Daily S&P 500 3x Bull",
    direction: "SELL",
    confidence: 81,
    assetClass: "ETFs",
    currentPrice: 67.32,
    changePercent: -2.67,
    entry: 69.50,
    stopLoss: 73.25,
    target: 62.00,
    riskReward: 2.18,
    atr: 3.85,
    maxPosition: 25000,
    triggeringEvent: "Overbought RSI + divergence",
    tags: ["levered-etf", "us-market", "technical"],
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "sig_005",
    ticker: "USDINR",
    name: "USD/INR Pair",
    direction: "BUY",
    confidence: 71,
    assetClass: "Forex",
    currentPrice: 83.45,
    changePercent: 1.56,
    entry: 83.00,
    stopLoss: 82.50,
    target: 84.50,
    riskReward: 2.0,
    atr: 0.28,
    maxPosition: 100000,
    triggeringEvent: "RBI hawkish signals + rate differentials",
    tags: ["forex", "emerging-market", "macro"],
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "sig_006",
    ticker: "BTC",
    name: "Bitcoin",
    direction: "BUY",
    confidence: 78,
    assetClass: "Crypto",
    currentPrice: 68420.50,
    changePercent: 4.32,
    entry: 66800.00,
    stopLoss: 64500.00,
    target: 72500.00,
    riskReward: 2.87,
    atr: 1850.75,
    maxPosition: 50000,
    triggeringEvent: "Breaking above 200-day MA + spot ETF inflows",
    tags: ["crypto", "bitcoin", "accumulation"],
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "sig_007",
    ticker: "LMT",
    name: "Lockheed Martin",
    direction: "BUY",
    confidence: 69,
    assetClass: "Equities",
    currentPrice: 512.87,
    changePercent: 1.94,
    entry: 503.00,
    stopLoss: 490.00,
    target: 545.00,
    riskReward: 2.15,
    atr: 12.45,
    maxPosition: 60000,
    triggeringEvent: "Defense spending uptick + geopolitical tensions",
    tags: ["defense", "us-stocks", "sector-rotation"],
    timestamp: new Date(Date.now() - 7 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "sig_008",
    ticker: "TCS",
    name: "Tata Consultancy Services",
    direction: "HOLD",
    confidence: 58,
    assetClass: "Equities",
    currentPrice: 3654.20,
    changePercent: -0.85,
    entry: 3700.00,
    stopLoss: 3550.00,
    target: 3850.00,
    riskReward: 1.5,
    atr: 89.30,
    maxPosition: 80000,
    triggeringEvent: "Profit booking after rally + mixed guidance",
    tags: ["it", "largecap", "consolidation"],
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "sig_009",
    ticker: "HDFCBANK",
    name: "HDFC Bank",
    direction: "BUY",
    confidence: 73,
    assetClass: "Equities",
    currentPrice: 1687.45,
    changePercent: 2.56,
    entry: 1645.00,
    stopLoss: 1600.00,
    target: 1800.00,
    riskReward: 3.1,
    atr: 32.15,
    maxPosition: 90000,
    triggeringEvent: "Strong Q4 results + rate cut cycle begins",
    tags: ["banking", "largecap", "dividend"],
    timestamp: new Date(Date.now() - 9 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "sig_010",
    ticker: "INFY",
    name: "Infosys Limited",
    direction: "SELL",
    confidence: 64,
    assetClass: "Equities",
    currentPrice: 1842.50,
    changePercent: -1.32,
    entry: 1865.00,
    stopLoss: 1910.00,
    target: 1750.00,
    riskReward: 2.0,
    atr: 45.60,
    maxPosition: 85000,
    triggeringEvent: "Weak forward guidance + margin compression",
    tags: ["it", "largecap", "technical-weakness"],
    timestamp: new Date(Date.now() - 10 * 60 * 60 * 1000),
    isActive: true,
  },
]

export const MARKET_CENTERS: MarketCenter[] = [
  {
    id: "mc_001",
    name: "New York",
    code: "NYSE",
    x: 120,
    y: 280,
    riskScore: 45,
    index: "S&P 500",
    indexValue: 5385.62,
    change: 1.23,
  },
  {
    id: "mc_002",
    name: "London",
    code: "LSE",
    x: 380,
    y: 200,
    riskScore: 38,
    index: "FTSE 100",
    indexValue: 8024.45,
    change: 0.87,
  },
  {
    id: "mc_003",
    name: "Tokyo",
    code: "JPX",
    x: 700,
    y: 150,
    riskScore: 52,
    index: "Nikkei 225",
    indexValue: 33458.29,
    change: 2.15,
  },
  {
    id: "mc_004",
    name: "Mumbai",
    code: "NSE",
    x: 520,
    y: 380,
    riskScore: 48,
    index: "NIFTY 50",
    indexValue: 22847.45,
    change: -1.23,
  },
  {
    id: "mc_005",
    name: "Shanghai",
    code: "SSE",
    x: 650,
    y: 320,
    riskScore: 56,
    index: "Shanghai Composite",
    indexValue: 3089.52,
    change: -0.45,
  },
  {
    id: "mc_006",
    name: "Frankfurt",
    code: "XE",
    x: 395,
    y: 180,
    riskScore: 42,
    index: "DAX",
    indexValue: 18841.76,
    change: 1.56,
  },
  {
    id: "mc_007",
    name: "Singapore",
    code: "SGX",
    x: 620,
    y: 400,
    riskScore: 35,
    index: "Straits Times Index",
    indexValue: 3542.89,
    change: 0.92,
  },
  {
    id: "mc_008",
    name: "Sydney",
    code: "ASX",
    x: 730,
    y: 450,
    riskScore: 44,
    index: "ASX 200",
    indexValue: 7845.67,
    change: 1.34,
  },
  {
    id: "mc_009",
    name: "Hong Kong",
    code: "HKEX",
    x: 680,
    y: 340,
    riskScore: 54,
    index: "Hang Seng",
    indexValue: 16258.43,
    change: -0.78,
  },
]

export const GEO_EVENTS: GeoEvent[] = [
  {
    id: "evt_001",
    title: "ECB Interest Rate Decision",
    time: "14:15 CET",
    region: "Europe",
    severity: "CRITICAL",
    impact: "Potential 2-3% volatility in EUR pairs and European equities",
  },
  {
    id: "evt_002",
    title: "US Initial Jobless Claims",
    time: "12:30 EST",
    region: "North America",
    severity: "HIGH",
    impact: "Labor market strength indicator affecting USD and equity indices",
  },
  {
    id: "evt_003",
    title: "China Manufacturing PMI",
    time: "09:00 CST",
    region: "Asia",
    severity: "MEDIUM",
    impact: "Economic growth indicator for Asia-Pacific region",
  },
  {
    id: "evt_004",
    title: "RBI Monetary Policy Meeting",
    time: "10:00 IST",
    region: "India",
    severity: "HIGH",
    impact: "INR volatility and Indian equity market movement expected",
  },
  {
    id: "evt_005",
    title: "Bank of Japan Press Conference",
    time: "15:30 JST",
    region: "Asia",
    severity: "MEDIUM",
    impact: "JPY strengthening expected, carry trade adjustments",
  },
  {
    id: "evt_006",
    title: "US CPI Release",
    time: "12:30 EST",
    region: "North America",
    severity: "CRITICAL",
    impact: "Inflation data affecting Fed policy expectations and all risk assets",
  },
  {
    id: "evt_007",
    title: "Eurozone Retail Sales",
    time: "10:00 CET",
    region: "Europe",
    severity: "LOW",
    impact: "Consumer spending indicator for European economy",
  },
  {
    id: "evt_008",
    title: "Federal Reserve FOMC Meeting",
    time: "18:00 EST",
    region: "North America",
    severity: "CRITICAL",
    impact: "Major decision on US interest rates affecting global markets",
  },
]

export const PORTFOLIO_HOLDINGS: PortfolioHolding[] = [
  {
    id: "hold_001",
    ticker: "XAUUSD",
    name: "Gold Futures",
    direction: "LONG",
    entry: 2120.00,
    current: 2145.50,
    quantity: 25,
    pnl: 638.75,
    pnlPercent: 1.20,
    weight: 18.5,
    status: "active",
    addedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
  },
  {
    id: "hold_002",
    ticker: "NIFTY50",
    name: "NIFTY 50 Index",
    direction: "LONG",
    entry: 23100.00,
    current: 22847.45,
    quantity: 10,
    pnl: -2525.50,
    pnlPercent: -1.09,
    weight: 22.0,
    status: "active",
    addedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
  },
  {
    id: "hold_003",
    ticker: "RELIANCE",
    name: "Reliance Industries",
    direction: "LONG",
    entry: 2920.00,
    current: 2987.65,
    quantity: 50,
    pnl: 3382.50,
    pnlPercent: 2.32,
    weight: 15.2,
    status: "active",
    addedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
  },
  {
    id: "hold_004",
    ticker: "BTC",
    name: "Bitcoin",
    direction: "LONG",
    entry: 66800.00,
    current: 68420.50,
    quantity: 0.5,
    pnl: 810.25,
    pnlPercent: 2.43,
    weight: 19.8,
    status: "active",
    addedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
  },
  {
    id: "hold_005",
    ticker: "HDFCBANK",
    name: "HDFC Bank",
    direction: "LONG",
    entry: 1645.00,
    current: 1687.45,
    quantity: 100,
    pnl: 4245.00,
    pnlPercent: 2.58,
    weight: 12.5,
    status: "active",
    addedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
  },
  {
    id: "hold_006",
    ticker: "INFY",
    name: "Infosys Limited",
    direction: "SHORT",
    entry: 1865.00,
    current: 1842.50,
    quantity: 75,
    pnl: 1687.50,
    pnlPercent: 1.20,
    weight: 12.0,
    status: "active",
    addedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },
]

export const FAQS: FAQ[] = [
  {
    id: "faq_001",
    question: "What is Alpha Terminal?",
    answer:
      "Alpha Terminal is a comprehensive trading dashboard and signal generation platform designed for institutional and retail traders. It provides real-time market analysis, geopolitical risk assessment, AI-powered trading signals, and portfolio management tools.",
    order: 1,
  },
  {
    id: "faq_002",
    question: "How accurate are the trading signals?",
    answer:
      "Our signals are generated using a combination of technical analysis, machine learning models, and macro fundamental analysis. Average accuracy rates vary by asset class and market conditions, but our system typically achieves 65-80% win rates in backtests. Past performance does not guarantee future results.",
    order: 2,
  },
  {
    id: "faq_003",
    question: "What markets can I trade with Alpha Terminal?",
    answer:
      "Alpha Terminal covers multiple asset classes including Equities (stocks and indices), Commodities (gold, crude oil, etc.), Forex (major and emerging pairs), Cryptocurrencies (Bitcoin, Ethereum, etc.), ETFs, and Bonds. Global markets including US, Indian, and Asian exchanges are supported.",
    order: 3,
  },
  {
    id: "faq_004",
    question: "Is there a minimum account size requirement?",
    answer:
      "No minimum account size is required to use Alpha Terminal. Our free tier allows you to access basic signals and 1-month data history. Pro and Enterprise tiers offer additional features without minimum account requirements, though your broker may have their own minimums.",
    order: 4,
  },
  {
    id: "faq_005",
    question: "Can I integrate Alpha Terminal with my broker?",
    answer:
      "Yes, we support integrations with major brokers through API connections. We currently have direct integrations with TD Ameritrade, Interactive Brokers, Zerodha, Angel Broking, and others. Custom integrations are available for Enterprise users.",
    order: 5,
  },
  {
    id: "faq_006",
    question: "How often are signals updated?",
    answer:
      "Our signals are updated in real-time during market hours. The system processes market data every minute for intraday signals and daily for swing/position trading signals. Geopolitical risk scores update every 4 hours based on global news feeds and sentiment analysis.",
    order: 6,
  },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "test_001",
    quote:
      "Alpha Terminal has transformed my trading approach. The combination of technical signals and geopolitical analysis gives me an edge I didn't have before.",
    name: "Rajesh Kumar",
    title: "Proprietary Trader",
    company: "Independent",
    rating: 5,
  },
  {
    id: "test_002",
    quote:
      "The risk metrics and portfolio exposure tools are invaluable. I've reduced my drawdowns significantly since implementing Alpha Terminal's recommendations.",
    name: "Priya Sharma",
    title: "Portfolio Manager",
    company: "Quantum Investments",
    rating: 5,
  },
  {
    id: "test_003",
    quote:
      "Finally, a trading platform that understands the importance of geopolitical context. This has helped me avoid several catastrophic events.",
    name: "Mark Anderson",
    title: "Hedge Fund Manager",
    company: "Global Alpha Fund",
    rating: 5,
  },
]

export const RISK_METRICS: RiskMetric[] = [
  {
    sector: "Technology",
    exposure: 28.5,
    volatility: 18.2,
    correlation: 0.72,
    var95: 3.45,
  },
  {
    sector: "Finance",
    exposure: 22.3,
    volatility: 15.8,
    correlation: 0.68,
    var95: 2.87,
  },
  {
    sector: "Healthcare",
    exposure: 15.7,
    volatility: 12.4,
    correlation: 0.52,
    var95: 1.94,
  },
  {
    sector: "Energy",
    exposure: 12.2,
    volatility: 21.5,
    correlation: 0.85,
    var95: 4.23,
  },
  {
    sector: "Commodities",
    exposure: 11.8,
    volatility: 19.7,
    correlation: 0.41,
    var95: 3.76,
  },
  {
    sector: "Emerging Markets",
    exposure: 9.5,
    volatility: 24.3,
    correlation: 0.78,
    var95: 5.12,
  },
  {
    sector: "Fixed Income",
    exposure: 8.2,
    volatility: 8.9,
    correlation: 0.35,
    var95: 1.23,
  },
  {
    sector: "Crypto",
    exposure: 7.8,
    volatility: 52.3,
    correlation: 0.62,
    var95: 9.87,
  },
]

export const PRICING_TIERS: PricingTier[] = [
  {
    id: "tier_001",
    name: "Starter",
    price: 0,
    features: [
      "5 trading signals per day",
      "1 month data history",
      "Basic market centers",
      "Email alerts",
      "Mobile app access",
    ],
    description: "Perfect for beginners exploring algorithmic trading",
  },
  {
    id: "tier_002",
    name: "Professional",
    price: 99,
    features: [
      "Unlimited trading signals",
      "1 year data history",
      "Advanced risk metrics",
      "Geopolitical risk scores",
      "Real-time notifications",
      "Portfolio analysis tools",
      "API access",
      "Priority support",
    ],
    description: "For active traders and portfolio managers",
    highlighted: true,
  },
  {
    id: "tier_003",
    name: "Enterprise",
    price: 499,
    features: [
      "Everything in Professional",
      "Custom signal strategies",
      "Dedicated account manager",
      "White-label platform",
      "Custom integrations",
      "Advanced backtesting",
      "Institutional support",
      "SLA guarantee",
      "Multi-user team access",
    ],
    description: "For institutions and trading firms",
  },
]

export const NAVIGATION_ITEMS: NavItem[] = [
  {
    label: "Home",
    href: "/",
  },
  {
    label: "Terminal",
    href: "/terminal",
    badge: "Live",
  },
  {
    label: "Pricing",
    href: "/pricing",
  },
  {
    label: "About",
    href: "/about",
  },
  {
    label: "Resources",
    href: "#",
    children: [
      {
        label: "Blog",
        href: "/blog",
      },
      {
        label: "Docs",
        href: "/docs",
      },
      {
        label: "FAQs",
        href: "/faqs",
      },
    ],
  },
  {
    label: "Contact",
    href: "/contact",
  },
]
